url: http://weddingmusic-OWL.de
baseurl: ""

# Site settings
title: WeddingMusic OWL
email: info@weddingmusic-owl.de
description: "WeddingMusic OWL - Die musikalische Unterst체tzung f체r Ihre Trauung "

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 4e326e 
  secondary: 9484a8
  secondary-dark: 191919

# Team names, titles and social links
people:
- name: Tobias Koehn
  pic: 2
  position: Pianist, S채nger
  social:
    - title: twitter
      url: http://twitter.com/tokoehn
    - title: facebook
      url: https://www.facebook.com/ToKoehn
    - title: envelope
      url: mailto:info@weddingmusic-owl.de
    - title: phone
      url: tel:+4915732520000

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/tokoehn
  - title: facebook
    url: https://www.facebook.com/ToKoehn


# Postal address (add as many lines as necessary)
address:
  - line: H체fferweg 27
  - line: 33100 Paderborn

# Build settings
markdown: kramdown
